#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Sandra Montejano Cánovas

# Short bio or description (displayed in the header)
description: Blog de la asignatura de Visión Robótica, donde iré publicando las actualizaciones de mis prácticas.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
# Cambia la URL aquí para poner la imagen que subiste a 'assets/images/foto-perfil.jpg'
avatar: /images/header-vision-robotica.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  github: tu-usuario  # Reemplaza con tu nombre de usuario de GitHub
  twitter: tuusuario  # Reemplaza con tu nombre de usuario de Twitter
  # Añadir otros enlaces de redes sociales si lo deseas

# Enter your Disqus shortname (not your username) to enable commenting on posts
# Puedes dejar esto vacío si no estás usando Disqus
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# Puedes dejar esto vacío si no estás usando Google Analytics
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://tu-usuario.github.io"  # Asegúrate de poner tu URL aquí

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""  # Deja vacío si estás usando la raíz del repositorio

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded  # Puedes usar :compressed si prefieres que el CSS sea más pequeño

# Use the following plug-ins
gems:
  - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed  # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
